### ISSUE TITLE
Check please: Boot with BIOS V1.7

### ISSUE THREAD

**Issue by kaneske** [igarashikenshin/Hackintosh-MSI-Z690-EDGE-TWD4_i7-12700K_RX6800XT#5]
Hi,

since BIOS Update 1.7 MSI Boards lost boot.
Keeps ending in: EXIT:LOG:BS:START

none of the Dortania or standard procdures help with this issue.

Can you please verify, that your Build is affected too? (Downgrade should be a walk in the Park)
May you've got a solution...

**Comment by igarashikenshin** [comment]
edit config.plist setvirtualmap enable

发自我的 iPhone

在 2022年8月17日，21:37，kaneske ***@***.***> 写道：

﻿

Hi,

since BIOS Update 1.7 MSI Boards lost boot.
Keeps ending in: EXIT:LOG:BS:START

none of the Dortania or standard procdures help with this issue.

Can you please verify, that your Build is affected too? (Downgrade should be a walk in the Park)
May you've got a solution...

**Comment by igarashikenshin** [comment]
Fix MSI BIOS E7D31IMS.A70 EB Err Problem：Edit Opencore config.plist file Set Booter-Quirks-SetupVirtualMap-Enable
