### ISSUE TITLE
Which monitor did you use?

### ISSUE THREAD

**Issue by LavenderMP** [igarashikenshin/Hackintosh-MSI-Z690-EDGE-TWD4_i7-12700K_RX6800XT#6]
I notice that you are using 5k monitors which one did you buy? can i have taobao/tmall url?

**Comment by igarashikenshin** [comment]
No, the monitor I'm using is a 4k display. The 5k display information you see is caused by me turning on hidpi. The display model I'm using is KTC M27P20. I bought it from JD.com. Unfortunately, its support for Intel Mac is not good. Its maximum refresh rate can only support ***@***.*** (No HDR), and its HDR colour gamut coverage is incomplete. I don't recommend it.

发自我的 iPhone

在 2022年10月16日，19:04，LavenderMP ***@***.***> 写道：

﻿

I notice that you are using 5k monitors which one did you buy? can i have taobao/tmall url?

**Comment by LavenderMP** [comment]
thanks!!
